openapi: 3.0.0
info:
  title: Test API
  version: "1.0"
paths:
  /token:
    get:
      summary: Submit user credentials and return a valid JWT
      responses:
        "401":
          description: Auth credentials not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/UnauthorizedPayload"
        "200":
          description: "Success response"
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/TokenPayload"
        "501":
          description: "Method not implemented"
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/NotImplementedPayload"
  /user:
    get:
      summary: User
      responses:
        "401":
          description: Auth credentials not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/UnauthorizedPayload"
        "200":
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/UserPayload"
        "501":
          description: "Method not implemented"
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/NotImplementedPayload"
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                request:
                  $ref: "#/components/schemas/CreateUserInput"
      responses:
        "201":
          description: Success response for creating a new user
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/CreateUserPayload"
        "409":
          description: Username must be unique
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/OperationFailed"
        "401":
          description: Username or password were not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    $ref: "#/components/schemas/OperationFailed"
components:
  schemas:
    CreateUserInput:
      title: CreateUserInput
      properties:
        username:
          type: string
        password:
          type: string
    OperationFailed:
      title: OperationFailed
      properties:
        error:
          type: boolean
        message:
          type: string
    CreateUserPayload:
      title: CreateUserPayload
      properties:
        success:
          type: boolean
    TokenPayload:
      title: TokenPayload
      properties:
        token:
          type: string
    NotImplementedPayload:
      title: InvalidRequestPayload
      properties:
        title:
          type: string
        description:
          type: string
    UnauthorizedPayload:
      title: UnauthorizedPayload
      properties:
        title:
          type: string
    UserPayload:
      title: UserPayload
      properties:
        profile_picture:
          type: string
        username:
          type: string
